forge "http://forge.puppetlabs.com"

  mod 'puppetlabs/stdlib'
 
  mod 'puppetlabs/wget'

  mod 'biemond/orawls'
  
  mod 'biemond/jdk7'
  
  mod 'biemond/orautils'

  mod 'fiddyspence/sysctl'
  
  mod 'erwbgy/limits'
